### ISSUE TITLE
Dont understand how to use it

### ISSUE THREAD

**Issue by DimaGolomozy** [kubukoz/sup#377] opened 2021-08-08 12:01 UTC
hi..
i want to create a simple HealthCheck. so Im doing this:
```
val health = HealthCheck.liftFBoolean[Id] {
   println("test")
   true
}
```
when Im running `health.check` **twice**,  i get a single "test" printed an this is because the `override val check` in the `liftF`
```
def liftF[F[_], H[_]](_check: F[HealthResult[H]]): HealthCheck[F, H] = new HealthCheck[F, H] {
    override val check: F[HealthResult[H]] = _check
  }
```

does that means that I can't reuse this HealhCheck? i need to recreate it every time? something like
```
//mongodb health check supplier
def getHealthCheck() = {
   HealthCheck.liftFBoolean[Id] {
     if (testMongo) true else false
   }
}
```

?

**Comment by kubukoz** [comment] 2021-08-09 20:57
Hi @DimaGolomozy, the library is designed to work with functional effects. By calling `println` in a block that evaluates to essentially `Boolean` you're eagerly executing a side effect.

The way to do this correctly (as in, in line with the design of the library) would be to use a referentially transparent (pure) effect type like [cats-effect IO](https://typelevel.org/cats-effect/):

```scala
import cats.effect.IO

val health = HealthCheck.liftFBoolean[IO] {
  IO.println("test") *> IO.pure(true)
}
```

Then it's going to behave as you want it to.

As for your `def getHealthCheck()`, that would indeed run the check every time you call `getHealthCheck`, but it's just pushing the problem to another layer (the call-site of `getHealthCheck` needs to be aware of the side effects). With a purely functional effect type like `IO`, `def foo()` and `val foo` are equivalent (because any effects will only happen when you run `foo` and not when you instantiate it).

**Comment by kubukoz** [comment] 2021-08-09 21:03
Feel free to ask follow-up questions if you need any more explanation, also if you're new to cats-effect we have a [Discord](https://discord.gg/HmPs7rAtEY).

I'll close this right now because the behavior is essentially "as intended" :)

**Closed by kubukoz** 2021-08-09 21:03 UTC
